baseURL = 'https://mcjones.ca'
languageCode = 'en-ca'
title = 'mcjones.ca'
theme = 'mcjones'
rssLimit = 50

[params]
[params.author]
  email = "chealion@chealion.ca"
  name = "Micheal Jones"

[markup.goldmark.renderer]
unsafe = true
